#! can throw away changes...was for testing
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-cf-workloads-egress
  namespace: cf-workloads
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          istio-injection: enabled
    - namespaceSelector:
        matchLabels:
          istio-injection: disabled
